### PR TITLE
document that django now only works on 2.0 or 2.1

### PR DESCRIPTION
**Pull request by barentine**
Addresses issue on django 1.11.29
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fdc858e73b0>
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/opt/miniconda3/lib/python3.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/miniconda3/lib/python3.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/miniconda3/lib/python3.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/opt/miniconda3/lib/python3.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/opt/miniconda3/lib/python3.7/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/opt/miniconda3/lib/python3.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/miniconda3/lib/python3.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/miniconda3/lib/python3.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/miniconda3/lib/python3.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/Andrew/code/python-microscopy/PYME/cluster/clusterUI/clusterUI/urls.py", line 17, in <module>
    from django.urls import include, path
ImportError: cannot import name 'include' from 'django.urls' (/opt/miniconda3/lib/python3.7/site-packages/django/urls/__init__.py)

```
following #774 

**Is this a bugfix or an enhancement?**
bugfix
**Proposed changes:**
make the docs right

### CODE REVIEW

**Comment by David-Baddeley** [comment]
I'd prefer a fix to the regression that stops it working on 1.11.x

**Comment by David-Baddeley** [comment]
issue fixed in #807, no need to rewrite docs
