### ISSUE TITLE
[PROPOSAL] update np.int / other dtype aliases for compatibility with numpy 1.24+

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#1449]
**Is your feature request related to a problem? Please describe.**
I did a pip install, whihc pulled numpy 1.24. Running the tests, I found some errors along the lines of:
```
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

the deprecation is described at the link [here](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations), and expired with 1.24 ([see here](https://numpy.org/devdocs/release/1.24.0-notes.html)).

**Describe the solution you'd like to implement**
First:
- PR to change requirements.txt to require numpy <1.24
- PR to change conda recipes to build with <1.24
Second:
- change the numpy aliases to their native types and then unpin numpy again

**Comment by barentine** [comment]
@David-Baddeley  looks like current pyme-depends (windows, py38 anyway) is pinned for numpy>1.22, so depending on what's in the anaconda channel for numpy folks might pull something disfunctional

**Comment by barentine** [comment]
more or less completed
